id: P6C5E0731
initial_creation_type: input
source_metadata:
  Title: Śikṣāsamuccayaḥ
  Editor: Vaidya, P. L.
  Publisher: The Mithila Institute of Post-Graduate Studies and Research in Sanskrit
    Learning
  Place of Publication: Darbhanga
  Year: '1960'
  Śikṣāsamuccaya kārikā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:43:40.074034'
last_modified_at: '2022-03-08T16:43:40.074041'
